name: CI/CD Pipeline
run-name: ${{ github.actor }} is running CI/CD pipeline

on:
  push:
    branches: [ Fabian, lydia, Malinda ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build (compile only, no tests)
        working-directory: code/app
        run: mvn -B -ntp clean package -DskipTests

      - name: Upload built jar
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: code/app/target/*.jar

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run unit tests + coverage
        working-directory: code/app
        run: mvn -B -ntp test

      - name: Upload test reports & coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage-reports
          path: |
            code/app/target/surefire-reports
            code/app/target/site/jacoco

  code-quality:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run Checkstyle (Google style)
        working-directory: code/app
        run: mvn -B -ntp checkstyle:check
